config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: 'home_pages#index'

  get 'policy', to: 'home_pages#policy'
  get 'terms', to: 'home_pages#terms'
  get 'hello_rails', to: 'home_pages#hello_rails'

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    post 'login', to: 'auth#login'
    post 'logout', to: 'auth#logout'

    resources :events
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/settings.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, 
         :omniauthable, omniauth_providers: %i[facebook]

  before_create :generate_authentication_token

  def self.from_omniauth(auth)
    # Find existing user by facebook uid
    existing_user = User.find_by_uid(auth.uid)
    if existing_user
      existing_user.fb_token = auth.credentials.token
      existing_user.save!
      return existing_user 
    end
       
    # Find existing user by email
    existing_user = User.find_by_email(auth.info.email)
    if existing_user
      existing_user.uid = auth.uid
      existing_user.provider = auth.provider
      existing_user.fb_token = auth.credentials.token
      existing_user.save!
      return existing_user
    end

    # Create new user
    user = User.new
    user.provider = auth.provider
    user.fb_token = auth.credentials.token
    user.uid = auth.uid
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.skip_confirmation!
    user.save!
    return user
  end

  def delete_access_token(auth)
    @graph ||= Koala::Facebook::API.new(auth.credentials.token)
    @graph.delete_connections(auth.uid, "permissions")
  end

  def generate_authentication_token
     self.authentication_token = Devise.friendly_token
  end

  # for api
  def self.get_fb_data(access_token)
    res = RestClient.get "https://graph.facebook.com/v2.5/me", {params: {access_token: access_token}}

    if res.code == 200
      JSON.parse(res.to_str)
    else
      Rails.logger.warn(res.body)
      nil
    end
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  before_action :authenticate_user_from_token!

  def authenticate_user_from_token!
    if params[:auth_token].present?
      user = User.find_by_authentication_token(params[:auth_token])
      sign_in(user, store: false) if user
    end
  end

end

app/controllers/api_v1/auth_controller.rb
class ApiV1::AuthController < ApiController
  before_action :authenticate_user!, only: [:logout]

  def login
    success = false

    if params[:email] && params[:password]
      user = User.find_by_email(params[:email])
      success = user && user.valid_password?(params[:password])
    elsif params[:access_token]
      fb_data = User.get_fb_data(params[:access_token])
      if fb_data
        auth_hash = OmniAuth::AuthHash.new({
          uid: fb_data["id"],
          info: {
            email: fb_data["email"]
          },
          credentials: {
            token: params[:access_token]
          }
        })
        user = User.from_omniauth(auth_hash)
      end

      success = fb_data && user.persisted?
    end

    if success
      render json: {message: "success",
                    auth_token: user.authentication_token,
                    user_id: user.id}
    else
      render json: { message: "Email or Password is wrong" }, status: 401
    end
  end

  def logout
    current_user.generate_authentication_token
    current_user.save!
    render json: { message: "success"}
  end

end

app/controllers/api_v1/events_controller.rb
class ApiV1::EventsController < ApiController
  before_action :authenticate_user!

  def index
    render json: { message: "Hi. #{current_user.id}" }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  
  def index
    set_meta_tags(site: '智慧科睿 | Your idea, I carry.', 
                  title: 'IntelligentCarry',
                  description: 'Intelligent Carry提供iOS/Android Mobile APP設計、網頁設計及使用者體驗優化服務。iOS APP design | Android APP design| iPhone design | iPAD design | 網頁設計 | web design | RWD design | UI/UX design',
                  keywords: 'app,web,ios,android,rwd,UX',
                  reverse: true,
                  og: {
                    site_name: "智慧科睿 iOS/Android/web design",
                    title: 'IntelligentCarry',
                    type: 'app and web design',
                    description: 'Intelligent Carry提供iOS/Android Mobile APP設計、網頁設計及使用者體驗優化服務。iOS APP design | Android APP design| iPhone design | iPAD design | 網頁設計 | web design | RWD design | UI/UX design',
                    url: 'http://www.intelligentcarry.com/'})
  end

  def hello_rails
  end

  def policy
  end

  def terms
  end

end

app/controllers/users/omniauth_callback_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])  # 這邊會呼叫我們在 user 中定義的創建行為
    
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      
      if @user.email.nil?
        # 如果 User 沒有提供 email 刪除 User 的 app 讓 User 重新授權
        @user.delete_access_token(request.env["omniauth.auth"])
        redirect_to new_user_registration_url, alert: "需要您同意 Email 授權唷！"
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end
  
  def failure
    redirect_to new_user_session_path, alert: "無法獲得驗證！"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      
      if @user.email.nil?
        # 如果 User 沒有提供 email 刪除 User 的 app 讓 User 重新授權
        @user.delete_access_token(request.env["omniauth.auth"])
        redirect_to new_user_registration_url, alert: "需要您同意 Email 授權唷！"
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url, alert: "#{@user.email}"
      end
    end
  end

  def failure
    redirect_to new_user_session_path, alert: "無法獲得驗證！"
  end
end

app/helpers/api_v1/events_helper.rb
module ApiV1::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home_pages/hello_rails.html.slim
.row
  .sm-12.md-12.col
    .paper
      .row.flex-center
        .text-center
          h1 Hello Rails
          h3 iCarry
  
  / .sm-12.md-4.col
  /   .paper
  /     .row.flex-center
  /       h2 Collapsibles
  /     .row
  /       .collapsible
  /         input id="collapsible1" type="checkbox" name="collapsible"
  /         label for="collapsible1" First
  /         .collapsible-body
  /           span Bacon ipsum dolor sit amet landjaeger sausage brisket, jerky drumstick fatback boudin ball tip turducken...
  /       .collapsible
  /         input id="collapsible2" type="checkbox" name="collapsible"
  /         label for="collapsible2" Second
  /         .collapsible-body
  /           span Bacon ipsum dolor sit amet landjaeger sausage brisket, jerky drumstick fatback boudin ball tip turducken...
  /       .collapsible
  /         input id="collapsible3" type="checkbox" name="collapsible"
  /         label for="collapsible3" Third
  /         .collapsible-body
  /           span Bacon ipsum dolor sit amet landjaeger sausage brisket, jerky drumstick fatback boudin ball tip turducken...

app/views/home_pages/index.html.slim
section
  .row.margin
    .col.col-12.index-full-screen-section.border
      .full-screen-content.text-center
        h1.no-margin
          span Your 
          span.main-color I
          span dea,
        h5.no-margin
          span ANDROID
          span.main-color = " × "
          span IOS
          span.main-color = " × "
          span WEBSITE
          span.main-color = " × "
          span UI/UX DESIGN
        h2.no-margin
          span I 
          span.main-color C
          span.opacity-6 arry.

section#about
  .row
    .col.col-12.text-center
      h2 About us      
      article.article
        p We are a young, dynamic and creative team that provides mobile application development, website development, database design, system planning, visual design and user experience optimization. Team members include project plans, UI/UX designer-to-program database planners, and cross-domain expertise to provide a full range of services. We are happy to use technology to solve problems in life and focus on the latest design trends, integrate into user habits, and do our best.

hr

section#services
  .row
    .col.col-12.text-center
      h2 Services
  .row.flex-edges
    .col.sm-4.text-center
      i.fa.fa-4x.fa-mobile.text-muted
      h3 Android/iOS Apps
      p Mobile APPs Design and Development. Bluetooth application. Mobile App Background and Server Management System. User Interface Design. Push Service.
    .col.sm-4.text-center
      i.fa.fa-4x.fa-connectdevelop.text-muted
      h3 Web Design
      p Web Design and Development. Responsive Web Design. API Integration and Development. Content Management System. SQL/NoSQL. E-commerce website development. SEO optimization.
    .col.sm-4.text-center
      i.fa.fa-4x.fa-users.text-muted
      h3 UI/UX Design
      p Create a pleasing experience for your device or application through visual and touching experience, visually provide a professional and friendly interface design, and promote the friendly interaction between the product and the user. In the technology world, connect people The temperature between people.

hr

section#portfolio
  / .row
    .col.col-12.text-center
      article.article.text-left
        = image_tag("index/3.jpg", class: "float-left max-width-400")
        | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non elit sed lorem vulputate consectetur sed vel orci. Nunc orci metus, hendrerit viverra diam a, viverra efficitur nisi. Suspendisse ante sapien, porta vitae augue et, pulvinar posuere nibh. Suspendisse id commodo sem, vestibulum malesuada erat. Duis luctus est sit amet nisl maximus porta. Curabitur tempor nisi tincidunt ultricies rutrum. Nam finibus turpis ut nibh dignissim, in tincidunt mauris suscipit. Curabitur sollicitudin mi quis orci semper, nec egestas nibh mollis. Aenean pellentesque lectus rutrum, ultrices felis malesuada, finibus purus. Morbi eleifend pellentesque justo, quis vestibulum mi. Donec porta ipsum tellus, ac scelerisque lectus pellentesque eget. Etiam quis rutrum dui. Nulla facilisi. Donec imperdiet mattis mi nec fringilla. Donec mollis augue sed viverra placerat. Donec varius, sem sed porttitor euismod, est nunc varius tellus, eget molestie urna arcu ac turpis. Phasellus id sem elit. Vivamus pellentesque mauris vel ex laoreet varius. Vivamus non tempor libero. Nam consectetur nisi erat, ac varius elit porttitor quis. Morbi ullamcorper, tortor in sagittis tempus, justo ipsum pretium urna, ut bibendum nisl orci et eros. Quisque ut ipsum neque. Integer sapien dolor, vestibulum id maximus ac, pharetra eu augue.
        = image_tag("index/uiux.jpg", class: "float-right max-width-500")
        | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non elit sed lorem vulputate consectetur sed vel orci. Nunc orci metus, hendrerit viverra diam a, viverra efficitur nisi. Suspendisse ante sapien, porta vitae augue et, pulvinar posuere nibh. Suspendisse id commodo sem, vestibulum malesuada erat. Duis luctus est sit amet nisl maximus porta. Curabitur tempor nisi tincidunt ultricies rutrum. Nam finibus turpis ut nibh dignissim, in tincidunt mauris suscipit. Curabitur sollicitudin mi quis orci semper, nec egestas nibh mollis. Aenean pellentesque lectus rutrum, ultrices felis malesuada, finibus purus. Morbi eleifend pellentesque justo, quis vestibulum mi. Donec porta ipsum tellus, ac scelerisque lectus pellentesque eget. Etiam quis rutrum dui. Nulla facilisi. Donec imperdiet mattis mi nec fringilla. Donec mollis augue sed viverra placerat. Donec varius, sem sed porttitor euismod, est nunc varius tellus, eget molestie urna arcu ac turpis. Phasellus id sem elit. Vivamus pellentesque mauris vel ex laoreet varius. Vivamus non tempor libero. Nam consectetur nisi erat, ac varius elit porttitor quis. Morbi ullamcorper, tortor in sagittis tempus, justo ipsum pretium urna, ut bibendum nisl orci et eros. Quisque ut ipsum neque. Integer sapien dolor, vestibulum id maximus ac, pharetra eu augue.
        = image_tag("index/2.jpg", class: "float-left max-width-500")
        | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non elit sed lorem vulputate consectetur sed vel orci. Nunc orci metus, hendrerit viverra diam a, viverra efficitur nisi. Suspendisse ante sapien, porta vitae augue et, pulvinar posuere nibh. Suspendisse id commodo sem, vestibulum malesuada erat. Duis luctus est sit amet nisl maximus porta. Curabitur tempor nisi tincidunt ultricies rutrum. Nam finibus turpis ut nibh dignissim, in tincidunt mauris suscipit. Curabitur sollicitudin mi quis orci semper, nec egestas nibh mollis. Aenean pellentesque lectus rutrum, ultrices felis malesuada, finibus purus. Morbi eleifend pellentesque justo, quis vestibulum mi. Donec porta ipsum tellus, ac scelerisque lectus pellentesque eget. Etiam quis rutrum dui. Nulla facilisi. Donec imperdiet mattis mi nec fringilla. Donec mollis augue sed viverra placerat. Donec varius, sem sed porttitor euismod, est nunc varius tellus, eget molestie urna arcu ac turpis. Phasellus id sem elit. Vivamus pellentesque mauris vel ex laoreet varius. Vivamus non tempor libero. Nam consectetur nisi erat, ac varius elit porttitor quis. Morbi ullamcorper, tortor in sagittis tempus, justo ipsum pretium urna, ut bibendum nisl orci et eros. Quisque ut ipsum neque. Integer sapien dolor, vestibulum id maximus ac, pharetra eu augue.
  .row.flex-edges
    .col.sm-4.text-center = image_tag("index/3.jpg", class: "border-2")
    .col.sm-4.text-center = image_tag("index/uiux.jpg", class: "border-4")
    .col.sm-4.text-center = image_tag("index/2.jpg", class: "border-6")


hr

section#contact
  .row
    .col.col-12.text-center
      h2 Contact us
      article.article
        p 希望我們的專業可以為您或您的企業解決需求，更期盼以我們的熱忱為您服務!!
        p 如果您有問題或意見，請與我們聯繫!!我們將很樂意幫助您找到最佳的解決方案。      
        i.fa.fa-phone.fa-3x
        p 02-2711-3681
        i.fa.fa-envelope-o.fa-3x
        p 
          a href="mailto:icarry.inc@gmail.com" icarry.inc@gmail.com

app/views/home_pages/policy.html.slim
.row
  .sm-12.md-12.col
    .paper
      .row.flex-center
        .text-center
          h1 隱私聲明

        .text-left
          p 
            網站及相關APP為智慧科睿有限公司（以下稱「本公司」）所經營之應用服務。本公司重視您的隱私權的保護，將依個人資料保護法及本隱私權保護政策之規範，妥適進行您的個人資料之蒐集、處理及利用。請您在使用本網站及相關APP前，先行審閱本隱私權保護政策
          p 
            span 1.本隱私權政策適用之範圍
            br
            span 本隱私權政策適用於所有本公司透過網站及相關APP向您蒐集之個人資料及其後續處理、利用行為。若您點選第三人網站之連結或廣告，拜訪各該網站或網頁時，有關您的隱私權保護，應依各該網站或網頁之經營者所定之隱私權政策規定處理，與本公司無涉。 請您在於使用相關服務前，確認您已審閱並同意本隱私權政策所列全部條款，若您不同意全部或部分者，則請勿使用相關服務。
          p
            span 2.個人資料保護法應告知事項
            br
            span = "(1)蒐集機關名稱：智慧科睿有限公司(2)蒐集目的：提供相關服務、廣告、行銷、客戶管理、會員管理、學術研究及其他與第三人合作之行銷推廣活動 (3)個人資料類別：識別類（姓名、職稱、地址、聯絡電話、電子郵件信箱）、特徵類（年齡、性別、出生年月日等）、社會情況類（興趣、休閒、消費模式等）、教育、技術或其他專業類（學歷）、受僱情形類（任職公司、薪資等）、健康與其他類、其他（往來電子郵件、網站留言、系統自動紀錄之軌跡資訊等）。 (4)個人資料利用期間：會員相關資料為會員有效期間及終止後六個月；因網站或應用服務使用所蒐集之資料（未與會員識別資料結合者），不受前開期間之限制。 (5)個人資料利用地區：本公司執行業務及伺服器主機所在地。 (6)個人資料利用對象：本公司、海內外關係企業及本公司委外之協力廠商（例如：提供物流、金流或活動贈品、試用品之廠商），如不含會員識別資料者，包含廣告機制合作廠商及特定廣告客戶；如為本公司與其他廠商共同蒐集者，將於該共同蒐集之活動中載明；如本公司有需要將可識別會員資料與他人合作者，將會另行取得會員同意。 (7)個人資料利用方式：依蒐集目的範圍及本隱私權政策進行利用。 (8)行使個人資料權利方式：依個人資料保護法第3條規定，您就您的個人資料享有查詢或請求閱覽、請求製給複製本、請求補充或更正、請求停止蒐集、處理或利用、請求刪除之權利。您可以透過寄送電子郵件至【icarry.inc@gmail.com】（為避免電子郵件系統漏信或其他原因無法收悉，以本公司回覆收悉為準）或以書面郵寄至【台北市大安區安和路一段 11 號 5 樓 107 室】方式行使上開權利，本公司將於收悉您的請求後，儘速處理。 (9)個人資料選填說明：若本公司於蒐集個人資料時，相關網頁或文件載明為選填者，僅為提供您使用相關服務更佳體驗，不影響您使用相關服務之權益。"
          p
            span 3.個人資料蒐集、處理及利用說明
            br
            span
              若您有使用Facebook或其他社群服務，本公司及海內外關係企業可能透過相關社群服務系統設計，於取得您的同意後，將部分網站的資訊發布於您的社群活動資訊頁面，若您不同意該等訊息之發布，請您勿點選同意鍵，或於事後透過各該社群服務之會員機制移除該等資訊或拒絕相關服務繼續發布相關訊息。若有任何問題，仍可與本公司聯絡，本公司將協助您確認、處理相關問題。 除依法應提供予司法、檢調機關、相關主管機關，或與本公司協力廠商為執行相關活動必要範圍之利用外，本公司將不會任意將您的個人資料提供予第三人。 當本公司或網站被其他第三者購併或收購資產，導致經營權轉換時，本公司會於事前將相關細節公告於網站，且本公司所擁有之全部或部分使用者資訊亦可能在經營權轉換的狀況下移轉給第三人。

          p
            span 4. Cookie技術
            br
            span 為便於日後的辨識，當您使用相關服務時，本公司可能會在您的電腦或其他連網設備上設定與存取Cookie或其他類似技術。 您可以透過設定您的個人電腦或上網設備，決定是否予許Cookie或其他類似技術的使用，若您關閉Cookie時，可能會造成您使用相關服務時之不便利或部分功能限制。
          
          p
            span 5.保密與安全性
            br
            span 對於所有在工作中有必要接觸使用者資料之員工，本公司對每位員工僅提供有限度之使用權限，以確保使用者的個人資料避免不當的取用或外洩。 為了保護您的帳戶及個人資料的安全，請您不要任意將個人帳號、密碼提供予第三人或允許第三人以您的個人資料申請帳號、密碼，否則，相關責任由您自行負擔。若您的帳號、密碼有外洩之虞，請您立即至更改密碼，或通知本公司暫停該帳號（本公司可能會要求核對您的個人資料）。 網際網路並不是一個安全的資訊傳輸環境，亦可能存在有心人士刻意透過社交或其他網站公開資訊蒐集之方式探知或蒐集您的個人資料，請您在使用相關服務時，避免將敏感的個人資料提供予他人或在網站上公開揭露。
          
          p
            span 6.未成年人保護
            br
            span 相關服務並非特別為未成年人/兒童設計，未成年人使用相關服務時，若同意本網站蒐集、利用其個人資訊時，應在法定代理人或監護人之同意下為之。法定代理人或監護人得隨時請求本公司停止特定帳號及其相關之個人資料之蒐集、處理及利用行為。
          
          p
            span 7.隱私權政策之修改
            br
            span 當本隱私權政策有任何對您個人資料權益之變更或修改時，本公司將會在相關服務公告，並以電子郵件通知您留存於相關服務之電子郵件信箱。若您不同意該等變更或修改，請停止繼續使用相關服務，並依本隱私權政策規定通知本公司停止蒐集、處理及利用您的個人資料。
    

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"
    meta name="title" content="iCarry智慧科睿"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = display_meta_tags
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = render 'shared/gtm'
  
  body
    = render 'shared/gtm_noscript'
    = render 'shared/facebook_sdk'
    = render 'shared/ga'

    = render 'shared/header'
    = render 'shared/flash_messages'

    = yield

app/views/shared/_facebook_sdk.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : <%= Settings.FACEBOOK_APP_ID %>,
      xfbml      : true,
      version    : 'v3.0'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_flash_messages.html.slim
- if flash[:notice] || flash[:alert] || flash[:error]
  .row.flex-spaces
    .sm-12.md-12.col
      - if flash[:notice]
        .alert.alert-success = flash[:notice]
      - if flash[:alert]
        .alert.alert-warning = flash[:alert]
      - if flash[:error]
        .alert.alert-danger = flash[:error]

app/views/shared/_header.html.slim
header
  .row.flex-space.shadow.shadow-small
    .col-6.col.text-left
      = link_to root_path
        span.main-color I
        span ntelligent
        span.main-color Carry
    
    - if action_name == 'index'
      .col-6.col.text-right.hidden-sm
        span.margin = link_to "CONTACT", "#contact"

    - else
      .col-6.col.text-right
        - if current_user
          span = "Hi, #{current_user.email}"
          = link_to '登出', destroy_user_session_path, :method => :delete, class: "paper-btn btn-small btn-warning no-margin"
        - else
          = link_to 'login', new_session_path(:user), class: "paper-btn btn-small btn-secondary no-margin"